services:
  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./.data/:/data:rw
    env_file:
      - .env
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD:-your_super_secret_password}",
      ]
    networks:
      - default

networks:
  default:
    name: redis-celery-network
